describe('Los estudiantes login', function() {
    it('Visits los estudiantes and fails at login', function() {
        cy.visit('https://losestudiantes.co')
        cy.contains('Cerrar').click()
        cy.contains('Ingresar').click()
        cy.get('.cajaLogIn').find('input[name="correo"]').click().type("jc.piza@uniandes.edu.co")
        cy.get('.cajaLogIn').find('input[name="password"]').click().type("1234567890")
        cy.get('.cajaLogIn').contains('Ingresar').click()
        cy.get('.Select-option-group-label').should('not.be.visible')
        cy.get('.Select-menu-outer').should('not.be.visible')
        cy.get('.Select-placeholder').click().type("mario linares vasquez")
        cy.get('.Select-option-group-label').should('be.visible')
        cy.get('.Select-menu-outer').should('be.visible')
        cy.get('.Select-option-group-label').should('contain', 'profesores')
        cy.get('#react-select-required_error_checksum--option-0').should('contain', 'Mario Linares Vasquez - Ingeniería de Sistemas')
        cy.get('#react-select-required_error_checksum--option-0').click()
        cy.url().should('eq', 'https://losestudiantes.co/universidad-de-los-andes/ingenieria-de-sistemas/profesores/mario-linares-vasquez')
    })
})